### ISSUE TITLE
这个模型可以在CPU上面运行吗？在train_SoftMaskedBert.yml文件里设置Device为CPU，把GPU_IDS注释掉之后还是会报错

### ISSUE THREAD

**Issue by A6Matrix** [gitabtion/BertBasedCorrectionModels#15]
![image](https://user-images.githubusercontent.com/18898570/125047350-76273600-e0d1-11eb-9013-8a5d9bf0b069.png)

![image](https://user-images.githubusercontent.com/18898570/125050488-93a9cf00-e0d4-11eb-8230-f4b407c34fae.png)

**Comment by gitabtion** [comment]
可以，DEVICE那里改成小写的cpu即可
