### ISSUE TITLE
训练报错！

### ISSUE THREAD

**Issue by jinxiang-unique** [gitabtion/BertBasedCorrectionModels#21]
![image](https://user-images.githubusercontent.com/59439162/137665144-90327562-427b-4929-aa1f-9b7e8725d207.png)
![image](https://user-images.githubusercontent.com/59439162/137665323-da87f31a-1612-4431-be7c-cbb5bc6428e3.png)

**Comment by kovnew** [comment]
> pytorch版本是多少呢？

同样遇到这个问题，torch版本是1.6.0
