### ISSUE TITLE
为什么精度这么高？

### ISSUE THREAD

**Issue by YouranShan** [gitabtion/BertBasedCorrectionModels#22]
为什么这个跑出来的精度比论文上的精度高那么多，就连bert的微调都可以达到state of the art？
一开始看训练数据量不一样，以为删除了脏数据所以提升，把训练数据全部加上去，精度还是很高，连bert微调都能当sota了。。。
为啥呀

**Comment by benbijituo** [comment]
数据不一样了。
这里的数据是作者自己预处理的，很多原有数据的噪音都没有了。你去和spellgcn使用的数据对比一下就知道了，很多不一样的地方。
mlm的权重spellgcn也用了。

**Comment by Dioxideme** [comment]
> 数据不一样了。 这里的数据是作者自己预处理的，很多原有数据的噪音都没有了。你去和spellgcn使用的数据对比一下就知道了，很多不一样的地方。 mlm的权重spellgcn也用了。

你好，能举例说一下哪些招银没有了吗，我简单对比了一下发现大部分数据都是一样的😂只发现了”著-着“这种情况
