### ISSUE TITLE
您好，请问一下bert4csc的字符级的实验结果是怎么算的呢

### ISSUE THREAD

**Issue by Floraox** [gitabtion/BertBasedCorrectionModels#27]
我跑起来看输出有sentence level的，另外是detection和correction的result，不明白是怎么得到您readme里写的char level的结果的呢

**Comment by gitabtion** [comment]
以每个token为单位计算即可

**Comment by Floraox** [comment]
看到您在别的issue里回答BERT4CSC是一个端到端的纠错网络，没有检错部分
![image](https://user-images.githubusercontent.com/37321391/143210057-d4035f91-9368-4140-9f44-0351a28d01c8.png)
所以这个结果应该是直接取的correction result吗？

**Comment by gitabtion** [comment]
@Floraox 上述结果是correction result，此外在5月份的更新中已经加入了检错网络，不过是以multi task，而非pipeline的形式。

**Comment by Floraox** [comment]
好的，感谢回答！
