### ISSUE TITLE
模型复现时的精度问题

### ISSUE THREAD

**Issue by Rafael8830** [gitabtion/BertBasedCorrectionModels#31]
您好！我在github readme中看到test的精度与论文有较大差异，请问这是因为test数据集不同导致的吗？如何才能达到论文上的精度呢？期待您的回复。
该项目的结果：
<img width="452" alt="c88b8b870086f42bc03bf76d095ba48" src="https://user-images.githubusercontent.com/47704881/150625525-740548e8-f31b-455b-8338-a1eccb45e545.png">
论文中的结果：
<img width="444" alt="116408b1e5300aa24500ebd7e24b829" src="https://user-images.githubusercontent.com/47704881/150625531-ac14d766-6566-4e2f-be31-17495bf8d983.png">

**Comment by gitabtion** [comment]
这个结果的correction是超越原paper中的结果的呀

**Comment by Haiming94** [comment]
> 您好！我在github readme中看到test的精度与论文有较大差异，请问这是因为test数据集不同导致的吗？如何才能达到论文上的精度呢？期待您的回复。 该项目的结果： <img alt="c88b8b870086f42bc03bf76d095ba48" width="452" src="https://user-images.githubusercontent.com/47704881/150625525-740548e8-f31b-455b-8338-a1eccb45e545.png"> 论文中的结果： <img alt="116408b1e5300aa24500ebd7e24b829" width="444" src="https://user-images.githubusercontent.com/47704881/150625531-ac14d766-6566-4e2f-be31-17495bf8d983.png">

这个结果有不同，我在想会不会是因为作者用的训练数据集是SIGHAN2014、2015和https://github.com/wdimmy/Automatic-Corpus-Generation/blob/master/corpus/train.sgml 的缘故呢，就是说这个代码用的训练数据集更加丰富，而原论文可能只单纯用了SIGHAN的数据。

**Comment by gitabtion** [comment]
1. 关于结果，单纯对比correction的sentence level acc即可，这里的实现是较原文要高出3个百分点左右的。
2. 关于数据，SMBERT原文中是有用字节内部的大量数据做预训练的，我们拿不到这个数据，所以只搜集了部分开源的数据做训练。

**Comment by Haiming94** [comment]
自动回复，您好，邮件已经收到，谢谢！

**Comment by Haiming94** [comment]
自动回复，您好，邮件已经收到，谢谢！
