### ISSUE TITLE
是用自己的数据集训练报错

### ISSUE THREAD

**Issue by nvliajia** [gitabtion/BertBasedCorrectionModels#32]
用作者的数据集训练可以，使用自己的数据集结果报错，
ValueError: Expected input batch_size (304) to match target batch_size (336).

我把自己的数据集融合到作者的数据集中也能训练，唯独无法单独训练自己的，不知道是不是还应该修改其他参数？

**Comment by gitabtion** [comment]
这套代码数据处理部分有点粗糙，兼容性可能差点，有需要的话您自己改改哈
