### ISSUE TITLE
Could you release softMaskedBert model for evaluation?

### ISSUE THREAD

**Issue by BrettLL** [gitabtion/BertBasedCorrectionModels#4]
Could you release softMaskedBert model for evaluation?

**Comment by gitabtion** [comment]
You can train the model yourself, and the results can be reproduced in less than 5 epochs.

**Comment by Yazooliu** [comment]
> Sorry, for the time being, there is no plan to release the trained checkpoints. You can train the model by yourself, and the results can be reproduced in less than 5 epochs.

Oh, I see this issue, now
Could I release this trained checkpoints by PR?
I saw this model file may 1.5G+ size and may update readme.md to add the model download link by cloud disk. 
thanks

Best Regards
Yazhou

**Comment by Yazooliu** [comment]
this PR is merged and issue is closed@BrettLL
