### ISSUE TITLE
请问如何在每个epoch里输出loss曲线？我找不到对应的位置，非常感谢～

### ISSUE THREAD

**Issue by LOGIC-10** [gitabtion/BertBasedCorrectionModels#40]

**Comment by gitabtion** [comment]
您可以参照[pytorch lightning](https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.loggers.wandb.html#module-pytorch_lightning.loggers.wandb)使用wandb logger输出各项指标的曲线
