### ISSUE TITLE
中文的某些符号问题

### ISSUE THREAD

**Issue by lixianwa** [gitabtion/BertBasedCorrectionModels#41]
你好！谢谢你的开源模型！
我在测试时发现，纠错的句子中如果包含某些中文符号时，结果中会出现"[UNK]", 这种情况如何处理呢？
```
texts = ['今天我很“高心”']
model.predict(texts)
```
results：
['今天我很[UNK]高兴[UNK]']

**Comment by gitabtion** [comment]
您好，确实会有这个问题。原因是引用的bert的词表不包含全角双引号，这个可以将两个unused token替换为全角双引号并重新训练。此外，本模型的训练集中不包含标点符号的纠错，所以您在输出纠错结果时可直接沿用原句的标点符号。
