### ISSUE TITLE
suggest to update this readme.md to show the model predict output result and format(output data type is list)

### ISSUE THREAD

**Issue by Yazooliu** [gitabtion/BertBasedCorrectionModels#43]
Hi, guy.
Good Job.

In readme.md file part 2:
from tools.inference import *
ckpt_fn = 'SoftMaskedBert/epoch=02-val_loss=0.02904.ckpt'  # find it in checkpoints/
config_file = 'csc/train_SoftMaskedBert.yml'  # find it in configs/
model = load_model_directly(ckpt_fn=ckpt_fn, config_file=config_file)
texts = ['今天我很高心', '测试', '继续测试']
model.predict(texts)

suggest to update this file to show the model predict output result and format(output data type is list).
Or please allow me to update by pull request ?
Keep talk.

Best Regards
Yazhou

**Comment by gitabtion** [comment]
Thans for your suggestion! If you have any ideas about further improving readme or other functions, please feel free to submit pr. Thank you very much for your contribution to BBCM!
