### ISSUE TITLE
将enconding改成unicode_escape后生成的train.json数据乱码

### ISSUE THREAD

**Issue by seanzhang-zhichen** [gitabtion/BertBasedCorrectionModels#5]

**Comment by seanzhang-zhichen** [comment]
![image](https://user-images.githubusercontent.com/74812416/111136542-d2ad9500-85b8-11eb-8c24-1b8a439161fe.png)
![image](https://user-images.githubusercontent.com/74812416/111136572-da6d3980-85b8-11eb-849a-8f5fd51ebda2.png)

**Comment by seanzhang-zhichen** [comment]
改成encoding=‘utf8’之后并加了error='ignore'才不报错。但是生成得数据id部分有些是一个（-），有些两个（--），请问是否会影响训练（我还没有仔细阅读源码，只是先跑起来），希望能得到您的回复，谢谢。
![image](https://user-images.githubusercontent.com/74812416/111137955-5c119700-85ba-11eb-9616-95a60e2339de.png)
![image](https://user-images.githubusercontent.com/74812416/111138023-6b90e000-85ba-11eb-90ea-0738dc3d31b3.png)

**Comment by gitabtion** [comment]
你好，id部分缺失不会影响到训练及预测。

**Comment by seanzhang-zhichen** [comment]
好的，感谢您的回复

**Comment by seanzhang-zhichen** [comment]
> 你好，id部分缺失不会影响到训练及预测。

运行inference.py时出现如下错误
![image](https://user-images.githubusercontent.com/74812416/111290068-bbd27580-8680-11eb-9b7b-e83433bf9cb0.png)

**Comment by gitabtion** [comment]
已更新推理脚本。

**Comment by seanzhang-zhichen** [comment]
> 已更新推理脚本。

太感人了，感谢作者，我试了一下，效果还不错，请问怎么才能拥有作者的联系方式

**Comment by gitabtion** [comment]
微信号: abtion

**Comment by Tisa-0** [comment]
> > 已更新推理脚本。
> 
> 太感人了，感谢作者，我试了一下，效果还不错，请问怎么才能拥有作者的联系方式
你好，你已经跑起来了吗，可以交流一下吗，这个可以对自己输入的文本纠错吗？
