### ISSUE TITLE
请教一下作者，在MacBert训练过程中，text_labels的Padding部分为什么要设置为-100

### ISSUE THREAD

**Issue by melonxi** [gitabtion/BertBasedCorrectionModels#9]
BertBasedCorrectionModels/bbcm/modeling/csc/modeling_bert4csc.py的第30行
`text_labels[text_labels == 0] = -100`
这里为什么要设置为-100呢，可以稍微解释一下吗，谢谢啦

**Comment by gitabtion** [comment]
在pytorch里，cross entropy loss默认不计算label为-100位置的loss，此为背景。此处，label==0意味着该处为pad的部分，是不应该计算loss的。

**Comment by melonxi** [comment]
> 在pytorch里，cross entropy loss默认不计算label为-100位置的loss，此为背景。此处，label==0意味着该处为pad的部分，是不应该计算loss的。

感谢解答！
